---
# Morphospace hyperparameters (per morphospace). Active morphospace: bpy.data.scenes["Scene"].traitblender_setup.available_morphospaces (default CO_Raup)
morphospace:
  name: CO_Raup
  hyperparams:
    CO_Raup:
      points_in_circle: 10
      time_step: 0.15
      use_inner_surface: false
world:
  color: [0.0, 0.0, 0.0, 1.0]
  strength: 1.0
camera:
  location: [0.0, 0.0, 1.0]
  aspect_x: 1.0
  aspect_y: 1.0
  camera_type: PERSP
  focal_length: 60.0
  lens_unit: MILLIMETERS
  resolution_percentage: 100
  resolution_x: 1080
  resolution_y: 1080
  rotation: [0.0, 0.0, 0.0]
  shift_x: 0.0
  shift_y: 0.0
lamp:
  location: [0.0, 0.0, 1.0]
  beam_blend: 0.0
  beam_size: 1.0
  color: [1.0, 1.0, 1.0]
  diffuse: 1.0
  power: 10.0
  rotation: [0.0, 0.0, 0.0]
  scale: [1.0, 1.0, 1.0]
  shadow: true
  use_soft_falloff: true
mat:
  color: [0.0, 0.0, 0.0, 1.0]
  location: [0.0, 0.0, 0.0]
  rotation: [0.0, 0.0, 0.0]
  roughness: 1.0
  scale: [0.125, 0.125, 1.0]
render:
  eevee_use_raytracing: false
  engine: BLENDER_EEVEE_NEXT
output:
  image_format: PNG
  images_per_view: 1
  output_directory: ""
  output_type: image
metadata:
  stamp_note_text: ""
  use_stamp_camera: true
  use_stamp_date: true
  use_stamp_filename: true
  use_stamp_frame: true
  use_stamp_frame_range: false
  use_stamp_hostname: false
  use_stamp_lens: false
  use_stamp_marker: false
  use_stamp_memory: false
  use_stamp_note: false
  use_stamp_render_time: true
  use_stamp_scene: true
  use_stamp_sequencer_strip: false
  use_stamp_time: true
transforms:
  [] 