schema_version = "1.0.0"

id = "traitblender"
version = "2.0.0"
name = "TraitBlender"
tagline = "Generate museum-style images for morphological datasets"
maintainer = "Caleb Charpentier <calebcharpentier00@gmail.com>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:MIT",
]

website = "https://github.com/Imageomics/TraitBlender"

wheels = [
  "./wheels/pandas-2.2.3-cp311-cp311-win_amd64.whl",
  "./wheels/numpy-2.2.6-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl",
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/pytz-2025.2-py2.py3-none-any.whl",
  "./wheels/tzdata-2025.2-py2.py3-none-any.whl",
  "./wheels/six-1.17.0-py2.py3-none-any.whl",
  "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
  "./wheels/scipy-1.16.0-cp311-cp311-win_amd64.whl",
  "./wheels/et_xmlfile-2.0.0-py3-none-any.whl",
  "./wheels/openpyxl-3.1.5-py2.py3-none-any.whl",
  "./wheels/dearpygui-2.0.0-cp311-cp311-win_amd64.whl"
]

[dependencies]
numpy = "./wheels/numpy-2.2.6-cp311-cp311-win_amd64.whl"
pandas = "./wheels/pandas-2.2.3-cp311-cp311-win_amd64.whl"
pillow = "./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl"
python_dateutil = "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl"
pytz = "./wheels/pytz-2025.2-py2.py3-none-any.whl"
PyYAML = "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl"
six = "./wheels/six-1.17.0-py2.py3-none-any.whl"
tzdata = "./wheels/tzdata-2025.2-py2.py3-none-any.whl"
scipy = "./wheels/scipy-1.16.0-cp311-cp311-win_amd64.whl"
et_xmlfile = "./wheels/et_xmlfile-2.0.0-py3-none-any.whl"
openpyxl = "./wheels/openpyxl-3.1.5-py2.py3-none-any.whl"
dearpygui = "./wheels/dearpygui-2.0.0-cp311-cp311-win_amd64.whl"

[permissions]
files = "Needed for reading trait data, assets, and morphospace models"
